name: panda
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10
  device_preview: ^1.2.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/